/* 合併翻譯字典 → js/i18n-dict.js
   來源：--src <dir> 下的 <lang>.json（key=繁中字串）＋ tools/i18n-geo.json（地區/國家名）。
   驗證：每個語言的 key 都必須在 tools/i18n-keys.json 內（geo 除外），並回報缺漏數。 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const srcIdx = process.argv.indexOf('--src');
const srcDir = srcIdx > -1 ? process.argv[srcIdx + 1] : join(root, 'tools', 'i18n-src');

const canonical = new Set(JSON.parse(readFileSync(join(root, 'tools', 'i18n-keys.json'), 'utf8')));
const geo = JSON.parse(readFileSync(join(root, 'tools', 'i18n-geo.json'), 'utf8'));

const dict = {};
for (const f of readdirSync(srcDir).filter((f) => f.endsWith('.json')).sort()) {
  const lang = f.replace(/\.json$/, '');
  const table = JSON.parse(readFileSync(join(srcDir, f), 'utf8'));
  let missing = 0, extra = 0;
  for (const k of canonical) if (table[k] === undefined) missing++;
  for (const k of Object.keys(table)) if (!canonical.has(k)) extra++;
  Object.assign(table, geo[lang] || {});
  dict[lang] = table;
  console.log(`${lang}: ${Object.keys(table).length} entries, missing ${missing}, extra ${extra}`);
}

const out = '/* 翻譯字典（generated by tools/i18n-merge.mjs — 手改請改來源後重跑合併） */\n' +
  'window.I18N_DICT = ' + JSON.stringify(dict) + ';\n';
writeFileSync(join(root, 'js', 'i18n-dict.js'), out);
console.log('js/i18n-dict.js written,', Math.round(out.length / 1024) + 'KB');
